# Generated by Django 5.1.4 on 2025-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'Danger'), ('high', 'High'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
